# Generated by Django 4.2.7 on 2023-11-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_remove_teacherdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdetails',
            name='department',
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='ourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.courses'),
        ),
    ]
